### ISSUE TITLE
'react-lineto-placeholder' divs only, no visible lines

### ISSUE THREAD

**Issue by dionjwa** [kdeloach/react-lineto#12]
![image](https://user-images.githubusercontent.com/260221/38478109-7d3742a0-3b6b-11e8-9b5f-fc7457313880.png)

I'm seeing the divs created with the `react-lineto-placeholder` class, but there's no visible lines. Admittedly this is in a larger application, but there's nothing to crazy going on. 

Any ideas why I don't see the lines? Using version `3.0.0`.

**Comment by kdeloach** [comment]
What code are you using? Try running the demo and compare your code against those examples.

**Comment by dionjwa** [comment]
It's too difficult to pull an isolated example, closing until able to.

**Comment by dhebert-dev** [comment]
I am having this same exact issue except I got the line to draw but it draws horizontally rather than vertically and the line is black rather than red which is what I specified in borderColor="red"
