### ISSUE TITLE
Dist files ship with a process polyfill?

### ISSUE THREAD

**Issue by arcanis** [kdeloach/react-lineto#13]
Is it expected? cf https://github.com/kdeloach/react-lineto/blob/master/dist/react-lineto.js#L237-L266

**Comment by Daniel15** [comment]
Hmm, I think it's because of `process.env` from `invariant`: https://github.com/kdeloach/react-lineto/blob/master/dist/react-lineto.js#L339

**Comment by Daniel15** [comment]
I think with React you're usually supposed to replace process.env.NODE_ENV
at build time - "development" for devs builds and "production" for prod
builds. This can be done in a Webpack config, for example.

**Comment by kdeloach** [comment]
Thanks for the advice. I set `process.env.NODE_ENV` to production and published build `3.1.0`. The bundle size is significantly smaller now.
