### ISSUE TITLE
ReferenceError: document is not defined when reload page.

### ISSUE THREAD

**Issue by oleglazarevich** [kdeloach/react-lineto#22]
This error happens each time when i reload a page with Lineto import.

The library works perfect if not doing reload to the page

**Comment by kdeloach** [comment]
Can't reproduce this. Do you have sample code?

**Comment by jonaswindey** [comment]
Do you use server side rendering? Then you have to load the component dynamically.

**Comment by joelwilsonmt** [comment]
I ran into the same problem using GatsbyJS, and couldn't find an easy way to split the code or load it dynamically, so I rewrote the parts I needed as a function component with a client check. It's quick and dirty, and only supports percentage toAnchor and fromAnchor, but it compiles:

`import React from 'react';

const defaultAnchor = { x: 0.5, y: 0.5 };
const defaultBorderColor = '#f00';
const defaultBorderStyle = 'solid';
const defaultBorderWidth = 1;

const isClient = typeof window === "object"

const findElement = (className) => {
    return isClient && document.getElementsByClassName(className)[0];
}

const parseAnchorPercent = (value) => {
    const percent = parseFloat(value) / 100;
    if (isNaN(percent) || !isFinite(percent)) {
        throw new Error(`LinkTo could not parse percent value "${value}"`);
    }
    return percent;
}

const parseAnchor = (value) => {
    if (!value) {
        return defaultAnchor;
    }
    const parts = value.split(' ');
    if (parts.length > 2) {
        throw new Error('LinkTo anchor format is "<x> <y>"');
    }
    const [x, y] = parts;
    return Object.assign({}, defaultAnchor,
        x ? { x: parseAnchorPercent(x) } : {},
        y ? { y: parseAnchorPercent(y) } : {}
    );
}

export default (props) => {
    const detect = () => {
        const { from, to, fromAnchor, toAnchor } = props;
        const a = findElement(from);
        const b = findElement(to);

        if (!a || !b) {
            return false;
        }

        const anchor0 = parseAnchor(fromAnchor);
        const anchor1 = parseAnchor(toAnchor);

        const box0 = a.getBoundingClientRect();
        const box1 = b.getBoundingClientRect();


        let offsetX = isClient && window.pageXOffset;
        let offsetY = isClient && window.pageYOffset;

        const x0 = box0.left + box0.width * anchor0.x + offsetX;
        const x1 = box1.left + box1.width * anchor1.x + offsetX;
        const y0 = box0.top + box0.height * anchor0.y + offsetY;
        const y1 = box1.top + box1.height * anchor1.y + offsetY;

        return { x0, y0, x1, y1 };
    }

    const points = detect();

    return points ? (
        <Line {...points} {...props} />
    ) : null;
}


const Line = (lineProps) => {
    const { x0, y0, x1, y1 } = lineProps;

    // const within = document.body;

    const dy = y1 - y0;
    const dx = x1 - x0;

    const angle = Math.atan2(dy, dx) * 180 / Math.PI;
    const length = Math.sqrt(dx * dx + dy * dy);

    const positionStyle = {
        position: 'absolute',
        top: `${y0}px`,
        left: `${x0}px`,
        width: `${length}px`,
        zIndex: Number.isFinite(lineProps.zIndex)
            ? String(lineProps.zIndex)
            : '1',
        transform: `rotate(${angle}deg)`,
        // Rotate around (x0, y0)
        transformOrigin: '0 0',
    };

    const defaultStyle = {
        borderTopColor: lineProps.borderColor || defaultBorderColor,
        borderTopStyle: lineProps.borderStyle || defaultBorderStyle,
        borderTopWidth: lineProps.borderWidth || defaultBorderWidth,
    };

    const props = {
        className: lineProps.className,
        style: Object.assign({}, defaultStyle, positionStyle),
    }

    // We need a wrapper element to prevent an exception when then
    // React component is removed. This is because we manually
    // move the rendered DOM element after creation.
    return (
        <div className="react-lineto-placeholder">
            <div
                ref={(el) => { el = el; }}
                {...props}
            />
        </div>
    );
}`
