### ISSUE TITLE
Support for ref

### ISSUE THREAD

**Issue by olso** [kdeloach/react-lineto#28]
To avoid using `className` we could use https://reactjs.org/docs/refs-and-the-dom.html

**Comment by RadoslavK** [comment]
It's been almost 2 years without any reply but I can see no reason for not doing so as it seems really intuitive that way.

**Comment by kdeloach** [comment]
You don't always have a ref to the objects you'd like to connect. Using class name allows you to connect objects without having to pass references. Of course, PRs are welcome.
