### ISSUE TITLE
Remove lifecycle warnings (componentWillMount, componentDidMount)

### ISSUE THREAD

**Issue by lxm7** [kdeloach/react-lineto#32]
`Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details`

It's the usual warning for lifecycle methods either needing to be renamed to UNSAFE_* or to use equivalent hooks. Cheers!

**Comment by juldrixx** [comment]
Same here

**Comment by tmg3** [comment]
If you would like assistance converting to hooks, please ask.

**Comment by tendo14** [comment]
https://github.com/kdeloach/react-lineto/pull/42 - Should fix this issue

**Comment by kdeloach** [comment]
Fixed in #42.
