### ISSUE TITLE
Drawn lines not displaying correctly

### ISSUE THREAD

**Issue by lema-fr** [kdeloach/react-lineto#39]
@kdeloach 

Hello, I'm using react-lineto in my app to draw lines between elements, but when a page is rendered for the first time, lines are not displaying correctly, for example, <LineTo from="B" to="C" borderStyle=" dashed" borderColor="#b8c6f2" borderWidth={1} delay={0} /> should be a vertical line between B&C, but when the page loads for the first time, this line doesn't go from "B" to "C", it goes way up from "C" and displays correctly only if I refresh the page or change screen size.
Could you please provide any tips on how to fix this?

Thank you.

**Comment by AlanQuadros** [comment]
Same problem

**Comment by brianjychan** [comment]
I had this problem, rendering the designated DOM elements, and then later rendering the <LineTo/> worked for me. For instance, use a `setTimeout` to trigger the state change that adds the <LineTo/> to the DOM

**Comment by kdeloach** [comment]
You can use the `delay` property to render lines after the target DOM elements are added. It uses `setTimeout` under the hood.
