### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by timcritt** [kdeloach/react-lineto#46]
Love the component by the way. It was exactly what I was looking for. I had a problem that I managed to solve, so thought I'd write a quick note here. 

I was getting this error while using the `<LineTo />` component. Here is the setup that produced it and how I fixed it.

I have two pages that make use of five `<LineTo />` components, each one inside an instance of another component, and with that component inside a div with the same class name on both pages. This is how it's structured. `<MyFirstPage>` is never rendered at the same time as `<MySecondPage>`.
```javascript
<MyFirstPage>
    <div className={"my-class"}>
//some other stuff here not found in second page
        <MyLineContainingComponent>
            <LineTo/>
            <LineTo/>
            <LineTo/>
            <LineTo/>
            <LineTo/>
          <MyLineContainingComponent />
     <div>
<MyFirstPage />
```
-------------------------------------------------------------------------------------------------------

```javascript
<MySecondPage>
    <div className={"my-class"}>
//some other stuff here not found in first page
        <MyLineContainingComponent>
            <LineTo/>
            <LineTo/>
            <LineTo/>
            <LineTo/>
            <LineTo/>
          <MyLineContainingComponent />
     <div>
<MySecondPage />
```

When I navigate to MyFirstPage, the lines display correctly. When I navigate directly to the second, the page renders but without the lines with no errors in the console. If I then navigate back to the first page directly from the second, I get the following error. 

"DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

The error is produced on line 378 of react-lineto.js when  `this.within.removeChild(this.el)` is called inside `componentWillUnmount()` when the second page unmounts. 

Providing unique class names to the container divs doesn't solve the issue. 

I fixed it by wrapping all the LineTo components in a div and providing them with a key that is unique to each instance. 

This isn't a problem unique to react-lineto, I think it's a problem that generally occurs when you manipulate the DOM directly instead of relying on React to do it. It took me a while to work out why this was happening, so I'm posting here in case someone has the same issue. Perhaps a warning about providing unique keys to the div that contains the `<LineTo />` component could be added to the readme.

**Comment by kdeloach** [comment]
I'm too far removed from frontend development these days to understand why this is happening. But thanks for the PR!
